export const mockParticipantRecord = {
  addictions: '',
  addressCity: 'Surrey',
  addressPostalCode: 'V1A1A1',
  addressProvince: 'British Columbia',
  addressStreet: '1234 1st St',
  addressTimeLivedAt: '5 years',
  admiresMost: 'My rival, who is the very best',
  allergies: 'Peanut butter',
  bankAccountType: 'Both',
  bcCareCardNumber: '9888888888',
  birthDate: '2004-10-31',
  children: '',
  citizenshipStatus: 'Canadian citizen',
  doctorName: 'Professor Oak',
  doctorPhone: '7781239999',
  driversLicenseType: 'New driver',
  email: 'Test@McTest.test',
  emergencyContact1Name: 'Mom',
  emergencyContact1PhoneCell: '6043332221',
  emergencyContact1PhoneHome: '6043334444',
  emergencyContact1PhoneWork: '7789993456',
  emergencyContact1Relationship: 'Mother',
  emergencyContact2Name: 'Dad',
  emergencyContact2PhoneCell: '6042223333',
  emergencyContact2PhoneHome: '2363339999',
  emergencyContact2PhoneWork: '6049091212',
  emergencyContact2Relationship: 'Father',
  employmentGoals: 'Be employed as the very best',
  employmentProgramComplete: 'Yes',
  employmentProgramInfo: 'Pokemon club, June 2019, Kanto',
  fears: 'Agoraphobia',
  formOfIncome: 'Part-time job',
  formOfIncomeOther: '',
  formOfTransportation: 'Bicycle',
  gender: 'Decline to answer',
  hasAccessToVehicle: 'No',
  hasBankAccount: 'Yes',
  hasChildren: 'No',
  hasEmploymentProgramTraining: 'Yes',
  hasHealthConcerns: 'No',
  hasMentalHealthIssues: 'Yes',
  hasResume: 'Yes',
  hasSiblings: 'No',
  hasTravelledOutsideBC: 'Yes',
  hasValidDriversLicense: 'Yes',
  hasVolunteered: 'No',
  healthConcerns: '',
  hobbies: 'Pokemon training',
  hopeToGainFromProgram: 'I want to be the very best',
  housingSituation: 'Homeless',
  housingSituationOther: '',
  inRehabOrAddictionsServices: 'No',
  indigenousGroup: 'Decline to answer',
  isEntitledToWorkInCanada: 'Yes',
  lawTrouble: 'Never',
  learnedAboutPathfinder: 'Other',
  learnedAboutPathfinderOther: 'Reddit',
  levelOfEducation: 'Decline to answer',
  medicalConditions: 'Asthma, Ventolin puffer',
  memberOfAVisibleMinority: 'Decline to answer',
  mentalHealthIssues: 'Anxiety',
  nameAndLocationOfSchool: 'Surrey Secondary School, Surrey, BC',
  nameGiven: 'Test',
  nameLast: 'McTest',
  newImmigrant: 'Decline to answer',
  numDependants: 0,
  numberOfJobInterviews: 5,
  personWithDisability: 'Decline to answer',
  personality: 'Shy/introverted',
  phoneCell: '7781111234',
  phoneHome: '6049991234',
  phoneHomeOrCell: 'Cell',
  physicalActivities: 'Pokemon gym',
  presentSituationAspects: ['Increase my self confidence', 'Other'],
  presentSituationAspectsOther: 'More snacks',
  programAppliedFor: 'Bean Around Books - Employment Experience',
  reasonsForUnemployment: ['I had no interest in working', 'Other'],
  reasonsForUnemploymentOther: "They told me 'Pokemon Master' was not a legitimate career choice",
  rent: 3.5,
  siblings: '',
  sin: '798428538',
  sixMonthsHistory: 'Learning to become the very best',
  skillsAndExperienceHopes: 'Becoming the very best',
  timeOutOfWork: 'Less than 6 months',
  urgentNeeds: [
    'The need to meet people in the same situation as me',
    'The need for personal growth and self-esteem',
  ],
  urgentNeedsOther: '',
  volunteerInfo: '',
  whyApplied: 'I am not the very best yet',
  whyShouldBeAccepted: 'I will be the best',
};